"""生成 K12 课标量级词库 data/words.json。

做法：
1. 读取现有 words.json（222 词，无 level 字段）→ 全部标为「初中」。
2. 合并下方 ADD 中按学段标注的新词（小学/初中/高中）。
3. 按 word 去重（大小写不敏感），写出完整词库。

重跑安全：每次都从「现有种子 + ADD」重建，去重保证幂等。
"""
import json
from pathlib import Path

BASE = Path(__file__).resolve().parent
WORDS_FILE = BASE / "data" / "words.json"

# ---------- 1. 读取现有种子（标为初中） ----------
seed = []
if WORDS_FILE.exists():
    try:
        seed = json.loads(WORDS_FILE.read_text(encoding="utf-8")).get("words", [])
    except Exception:
        seed = []
for w in seed:
    w.setdefault("level", "初中")

# ---------- 2. 新增分学段词库 ----------
# 每条：(word, pos, 中文释义, 学段, 英文例句, 中文翻译)
ADD = [
    # ===================== 小学（基础词） =====================
    ("apple", "n.", "苹果", "小学", "I eat an apple every day.", "我每天吃一个苹果。"),
    ("banana", "n.", "香蕉", "小学", "The monkey likes bananas.", "猴子喜欢香蕉。"),
    ("cat", "n.", "猫", "小学", "The cat is sleeping.", "猫在睡觉。"),
    ("dog", "n.", "狗", "小学", "My dog is very friendly.", "我的狗很友好。"),
    ("book", "n.", "书", "小学", "I read a book at night.", "我晚上看书。"),
    ("pen", "n.", "钢笔", "小学", "May I borrow your pen?", "我能借你的钢笔吗？"),
    ("pencil", "n.", "铅笔", "小学", "She draws with a pencil.", "她用铅笔画画。"),
    ("teacher", "n.", "老师", "小学", "Our teacher is kind.", "我们的老师很和蔼。"),
    ("student", "n.", "学生", "小学", "He is a good student.", "他是个好学生。"),
    ("school", "n.", "学校", "小学", "We go to school by bus.", "我们坐公交上学。"),
    ("home", "n.", "家", "小学", "I love my home.", "我爱我的家。"),
    ("family", "n.", "家庭", "小学", "This is my family.", "这是我的家人。"),
    ("mother", "n.", "妈妈", "小学", "My mother cooks dinner.", "妈妈做晚饭。"),
    ("father", "n.", "爸爸", "小学", "My father is tall.", "爸爸很高。"),
    ("friend", "n.", "朋友", "小学", "She is my best friend.", "她是我最好的朋友。"),
    ("red", "adj.", "红色的", "小学", "The apple is red.", "苹果是红色的。"),
    ("blue", "adj.", "蓝色的", "小学", "The sky is blue.", "天空是蓝色的。"),
    ("green", "adj.", "绿色的", "小学", "Grass is green.", "草是绿色的。"),
    ("yellow", "adj.", "黄色的", "小学", "The sun is yellow.", "太阳是黄色的。"),
    ("big", "adj.", "大的", "小学", "An elephant is big.", "大象很大。"),
    ("small", "adj.", "小的", "小学", "A mouse is small.", "老鼠很小。"),
    ("happy", "adj.", "开心的", "小学", "I am happy today.", "我今天很开心。"),
    ("sad", "adj.", "伤心的", "小学", "The child is sad.", "孩子很伤心。"),
    ("run", "v.", "跑", "小学", "He can run fast.", "他能跑得很快。"),
    ("jump", "v.", "跳", "小学", "The rabbit can jump.", "兔子会跳。"),
    ("eat", "v.", "吃", "小学", "We eat rice for lunch.", "我们午饭吃米饭。"),
    ("drink", "v.", "喝", "小学", "Drink some water.", "喝点水。"),
    ("sleep", "v.", "睡觉", "小学", "The baby is asleep.", "宝宝在睡觉。"),
    ("read", "v.", "读", "小学", "I read a story.", "我读了一个故事。"),
    ("write", "v.", "写", "小学", "Please write your name.", "请写下你的名字。"),
    ("play", "v.", "玩", "小学", "Children like to play.", "孩子们喜欢玩。"),
    ("sing", "v.", "唱歌", "小学", "She can sing well.", "她唱得很好。"),
    ("dance", "v.", "跳舞", "小学", "They dance at the party.", "他们在派对上跳舞。"),
    ("water", "n.", "水", "小学", "Water is important.", "水很重要。"),
    ("milk", "n.", "牛奶", "小学", "I drink milk every morning.", "我每天早晨喝牛奶。"),
    ("rice", "n.", "米饭", "小学", "We eat rice every day.", "我们每天吃米饭。"),
    ("egg", "n.", "鸡蛋", "小学", "I had an egg for breakfast.", "我早餐吃了一个蛋。"),
    ("sun", "n.", "太阳", "小学", "The sun is bright.", "太阳很明亮。"),
    ("moon", "n.", "月亮", "小学", "The moon is round.", "月亮是圆的。"),
    ("star", "n.", "星星", "小学", "Stars shine at night.", "星星在夜里闪烁。"),
    ("tree", "n.", "树", "小学", "A bird is in the tree.", "树上有一只鸟。"),
    ("flower", "n.", "花", "小学", "The flower is beautiful.", "这朵花很美。"),
    ("bird", "n.", "鸟", "小学", "A bird can fly.", "鸟会飞。"),
    ("fish", "n.", "鱼", "小学", "The fish is swimming.", "鱼在游泳。"),
    ("cow", "n.", "奶牛", "小学", "The cow gives milk.", "奶牛产奶。"),
    ("pig", "n.", "猪", "小学", "The pig is fat.", "猪很胖。"),
    ("go", "v.", "去", "小学", "Let's go to school.", "我们去上学吧。"),
    ("come", "v.", "来", "小学", "Come here, please.", "请过来。"),
    ("see", "v.", "看见", "小学", "I see a cat.", "我看见一只猫。"),
    ("look", "v.", "看", "小学", "Look at the blackboard.", "看黑板。"),
    ("hear", "v.", "听见", "小学", "I hear a song.", "我听见一首歌。"),
    ("open", "v.", "打开", "小学", "Open the door.", "开门。"),
    ("close", "v.", "关上", "小学", "Close the window.", "关窗。"),
    ("hot", "adj.", "热的", "小学", "The soup is hot.", "汤很烫。"),
    ("cold", "adj.", "冷的", "小学", "Winter is cold.", "冬天很冷。"),
    ("new", "adj.", "新的", "小学", "I have a new bag.", "我有一个新书包。"),
    ("old", "adj.", "旧的；老的", "小学", "My grandpa is old.", "爷爷年纪大了。"),
    ("good", "adj.", "好的", "小学", "This is a good book.", "这是本好书。"),
    ("bad", "adj.", "坏的", "小学", "The weather is bad.", "天气不好。"),
    ("fast", "adj./adv.", "快的", "小学", "A car is fast.", "汽车很快。"),
    ("slow", "adj./adv.", "慢的", "小学", "A snail is slow.", "蜗牛很慢。"),
    ("bag", "n.", "书包；袋子", "小学", "My bag is heavy.", "我的书包很重。"),
    ("desk", "n.", "书桌", "小学", "The book is on the desk.", "书在书桌上。"),
    ("chair", "n.", "椅子", "小学", "Sit on the chair.", "坐在椅子上。"),
    ("door", "n.", "门", "小学", "Open the door.", "开门。"),
    ("window", "n.", "窗户", "小学", "The window is clean.", "窗户很干净。"),
    ("ball", "n.", "球", "小学", "Kick the ball.", "踢球。"),
    ("kite", "n.", "风筝", "小学", "The kite flies high.", "风筝飞得高。"),
    ("toy", "n.", "玩具", "小学", "The child likes toys.", "孩子喜欢玩具。"),
    ("song", "n.", "歌曲", "小学", "She sings a song.", "她唱了一首歌。"),
    ("game", "n.", "游戏", "小学", "Let's play a game.", "我们玩个游戏吧。"),
    ("rain", "n./v.", "雨；下雨", "小学", "It is raining.", "下雨了。"),
    ("snow", "n./v.", "雪；下雪", "小学", "Snow is white.", "雪是白的。"),
    ("wind", "n.", "风", "小学", "The wind is strong.", "风很大。"),
    ("hand", "n.", "手", "小学", "Raise your hand.", "举手。"),
    ("foot", "n.", "脚", "小学", "My foot hurts.", "我的脚疼。"),
    ("head", "n.", "头", "小学", "He shakes his head.", "他摇了摇头。"),
    ("eye", "n.", "眼睛", "小学", "She has big eyes.", "她有大眼睛。"),
    ("ear", "n.", "耳朵", "小学", "My ear hurts.", "我耳朵疼。"),
    ("nose", "n.", "鼻子", "小学", "A dog has a good nose.", "狗鼻子灵。"),
    ("mouth", "n.", "嘴", "小学", "Open your mouth.", "张开嘴。"),
    ("face", "n.", "脸", "小学", "Wash your face.", "洗脸。"),
    ("hair", "n.", "头发", "小学", "She has long hair.", "她有长头发。"),
    ("boy", "n.", "男孩", "小学", "The boy is my brother.", "那男孩是我弟弟。"),
    ("girl", "n.", "女孩", "小学", "The girl is smiling.", "女孩在微笑。"),
    ("baby", "n.", "婴儿", "小学", "The baby is crying.", "宝宝在哭。"),
    ("man", "n.", "男人", "小学", "The man is a doctor.", "那男人是医生。"),
    ("woman", "n.", "女人", "小学", "The woman is a teacher.", "那女人是老师。"),
    ("child", "n.", "孩子", "小学", "The child is happy.", "孩子很开心。"),
    ("name", "n.", "名字", "小学", "What is your name?", "你叫什么名字？"),
    ("time", "n.", "时间；次", "小学", "What time is it?", "现在几点？"),
    ("morning", "n.", "早晨", "小学", "Good morning!", "早上好！"),
    ("evening", "n.", "晚上", "小学", "Good evening!", "晚上好！"),
    ("night", "n.", "夜晚", "小学", "Good night!", "晚安！"),
    ("day", "n.", "白天；一天", "小学", "Have a nice day!", "祝你今天愉快！"),
    ("week", "n.", "周", "小学", "There are 7 days in a week.", "一周有7天。"),
    ("year", "n.", "年", "小学", "A year has 12 months.", "一年有12个月。"),
    ("hello", "int.", "你好", "小学", "Hello, how are you?", "你好，最近好吗？"),
    ("thank", "v.", "谢谢", "小学", "Thank you very much.", "非常感谢你。"),
    ("please", "int.", "请", "小学", "Please sit down.", "请坐。"),
    ("sorry", "adj./int.", "抱歉", "小学", "I am sorry.", "对不起。"),
    ("love", "v.", "爱", "小学", "I love my family.", "我爱我的家人。"),
    ("like", "v.", "喜欢", "小学", "I like apples.", "我喜欢苹果。"),
    ("want", "v.", "想要", "小学", "I want a toy.", "我想要一个玩具。"),
    ("have", "v.", "有", "小学", "I have a book.", "我有一本书。"),
    ("color", "n.", "颜色", "小学", "What color is it?", "它是什么颜色？"),
    ("number", "n.", "数字", "小学", "Count the numbers.", "数一数这些数字。"),
    ("animal", "n.", "动物", "小学", "A cat is an animal.", "猫是动物。"),
    ("fruit", "n.", "水果", "小学", "An apple is a fruit.", "苹果是水果。"),
    ("food", "n.", "食物", "小学", "We need food to live.", "我们需要食物生存。"),

    # ===================== 初中（进阶词） =====================
    ("ability", "n.", "能力；才能", "初中", "She has the ability to solve problems.", "她有解决问题的能力。"),
    ("accept", "v.", "接受；同意", "初中", "I accept your invitation.", "我接受你的邀请。"),
    ("accident", "n.", "事故；意外", "初中", "He had a car accident.", "他出了车祸。"),
    ("achieve", "v.", "达到；实现", "初中", "You can achieve your dream.", "你能实现梦想。"),
    ("across", "prep.", "穿过；在对面", "初中", "Walk across the bridge.", "走过那座桥。"),
    ("action", "n.", "行动；行为", "初中", "We need to take action.", "我们需要行动。"),
    ("active", "adj.", "积极的；活跃的", "初中", "He is active in class.", "他在课上很积极。"),
    ("address", "n.", "地址；演说", "初中", "What is your address?", "你的地址是？"),
    ("advantage", "n.", "优势；优点", "初中", "Reading gives you an advantage.", "阅读让你有优势。"),
    ("advice", "n.", "建议（不可数）", "初中", "Can you give me some advice?", "你能给我些建议吗？"),
    ("afford", "v.", "负担得起", "初中", "We can't afford it.", "我们买不起。"),
    ("afraid", "adj.", "害怕的", "初中", "Don't be afraid.", "别害怕。"),
    ("agree", "v.", "同意", "初中", "I agree with you.", "我同意你。"),
    ("allow", "v.", "允许", "初中", "My parents allow me to go.", "父母允许我去。"),
    ("ancient", "adj.", "古老的", "初中", "China has ancient history.", "中国有古老历史。"),
    ("angry", "adj.", "生气的", "初中", "The teacher was angry.", "老师生气了。"),
    ("appear", "v.", "出现；显得", "初中", "Stars appear at night.", "星星在夜里出现。"),
    ("attention", "n.", "注意；专心", "初中", "Pay attention to the teacher.", "注意听老师讲。"),
    ("attract", "v.", "吸引", "初中", "Bright colors attract kids.", "鲜艳颜色吸引孩子。"),
    ("available", "adj.", "可获得的；有空的", "初中", "Is the book available?", "这本书有货吗？"),
    ("average", "adj./n.", "平均的；平均数", "初中", "The average score is 85.", "平均分是85。"),
    ("avoid", "v.", "避免", "初中", "Avoid the same mistake.", "避免犯同样错误。"),
    ("believe", "v.", "相信；认为", "初中", "I believe you can do it.", "我相信你能行。"),
    ("benefit", "n./v.", "好处；受益", "初中", "Exercise benefits health.", "运动有益健康。"),
    ("brave", "adj.", "勇敢的", "初中", "Be brave and try again.", "勇敢点再试一次。"),
    ("build", "v.", "建造；建立", "初中", "They build a house.", "他们建了房子。"),
    ("careful", "adj.", "小心的；仔细的", "初中", "Be careful crossing the road.", "过马路要小心。"),
    ("chance", "n.", "机会；可能性", "初中", "Give him a second chance.", "给他第二次机会。"),
    ("choose", "v.", "选择", "初中", "Choose the right answer.", "选正确答案。"),
    ("communicate", "v.", "交流；沟通", "初中", "We communicate by email.", "我们用邮件沟通。"),
    ("compare", "v.", "比较", "初中", "Compare the two pictures.", "比较这两幅图。"),
    ("compete", "v.", "竞争；比赛", "初中", "They compete for the prize.", "他们为奖品竞争。"),
    ("confident", "adj.", "自信的", "初中", "She is confident in public.", "她在众人前很自信。"),
    ("consider", "v.", "考虑；认为", "初中", "Consider my suggestion.", "考虑我的建议。"),
    ("continue", "v.", "继续", "初中", "Continue reading the text.", "继续读课文。"),
    ("control", "v./n.", "控制", "初中", "Control your temper.", "控制你的脾气。"),
    ("create", "v.", "创造；创作", "初中", "Artists create beauty.", "艺术家创造美。"),
    ("culture", "n.", "文化", "初中", "Food is part of culture.", "食物是文化的一部分。"),
    ("curious", "adj.", "好奇的", "初中", "Kids are curious about everything.", "孩子对世界充满好奇。"),
    ("decide", "v.", "决定", "初中", "I decided to study hard.", "我决定努力学习。"),
    ("depend", "v.", "依赖；取决于", "初中", "It depends on the weather.", "这要看天气。"),
    ("develop", "v.", "发展；开发", "初中", "Cities develop fast.", "城市发展很快。"),
    ("discover", "v.", "发现", "初中", "Columbus discovered America.", "哥伦布发现美洲。"),
    ("discuss", "v.", "讨论", "初中", "We discuss the plan.", "我们讨论计划。"),
    ("disease", "n.", "疾病", "初中", "Wash hands to avoid disease.", "洗手防疾病。"),
    ("effect", "n.", "效果；影响", "初中", "The medicine has an effect.", "这药有效。"),
    ("effort", "n.", "努力", "初中", "Hard effort brings success.", "努力带来成功。"),
    ("environment", "n.", "环境", "初中", "We must protect the environment.", "我们必须保护环境。"),
    ("encourage", "v.", "鼓励", "初中", "Parents encourage their kids.", "父母鼓励孩子。"),
    ("enough", "adj./adv.", "足够的", "初中", "We have enough time.", "我们有足够时间。"),
    ("experience", "n./v.", "经验；经历", "初中", "Travel is a great experience.", "旅行是很棒的经历。"),
    ("favorite", "adj./n.", "最喜欢的", "初中", "Blue is my favorite color.", "蓝色是我最爱的颜色。"),
    ("whether", "conj.", "是否；不管", "初中", "I don't know whether it will rain.", "我不知道是否会下雨。"),
    ("although", "conj.", "虽然；尽管", "初中", "Although it rained, we went out.", "虽然下雨我们还是出门了。"),
    ("unless", "conj.", "除非", "初中", "Don't go unless I call you.", "除非我叫你，否则别去。"),
    ("neighbor", "n.", "邻居", "初中", "Our neighbor is very kind.", "邻居很和蔼。"),
    ("realize", "v.", "意识到；实现", "初中", "I realized my mistake.", "我意识到了错误。"),
    ("require", "v.", "需要；要求", "初中", "The job requires patience.", "这工作需要耐心。"),
    ("research", "n./v.", "研究", "初中", "They do research on birds.", "他们研究鸟类。"),
    ("online", "adj./adv.", "在线的", "初中", "We study online.", "我们在线学习。"),
    ("perfect", "adj.", "完美的", "初中", "Nothing is perfect.", "没有什么是完美的。"),
    ("prevent", "v.", "防止；阻止", "初中", "Wash hands to prevent illness.", "洗手防生病。"),
    ("promise", "v./n.", "承诺", "初中", "He promised to help me.", "他答应帮我。"),
    ("purpose", "n.", "目的；意图", "初中", "What is the purpose of this?", "这目的是什么？"),
    ("quiet", "adj.", "安静的", "初中", "The library is quiet.", "图书馆很安静。"),
    ("raise", "v.", "举起；抚养", "初中", "Raise your hand.", "举手。"),
    ("reach", "v.", "到达；伸手", "初中", "We reached the top.", "我们到达了山顶。"),
    ("region", "n.", "地区；区域", "初中", "This region is beautiful.", "这个地区很美。"),
    ("remind", "v.", "提醒", "初中", "Remind me of the meeting.", "提醒我开会。"),
    ("respect", "v./n.", "尊敬", "初中", "We respect our teachers.", "我们尊敬老师。"),
    ("result", "n.", "结果", "初中", "The result is surprising.", "结果令人惊讶。"),
    ("return", "v.", "返回；归还", "初中", "When will you return?", "你何时回来？"),
    ("safe", "adj.", "安全的", "初中", "Keep your money safe.", "保管好你的钱。"),
    ("satisfy", "v.", "使满意", "初中", "The answer satisfied him.", "答案让他满意。"),
    ("score", "n./v.", "分数；得分", "初中", "He scored 90 points.", "他得了90分。"),
    ("search", "v./n.", "搜索；搜寻", "初中", "Search the word online.", "上网查这个词。"),
    ("secret", "n./adj.", "秘密", "初中", "Can you keep a secret?", "你能保密吗？"),
    ("sense", "n./v.", "感觉；意义", "初中", "She has a good sense of humor.", "她很有幽默感。"),
    ("serious", "adj.", "严肃的；严重的", "初中", "This is a serious problem.", "这是个严重问题。"),
    ("serve", "v.", "服务；端上", "初中", "The waiter serves food.", "服务员上菜。"),
    ("share", "v.", "分享", "初中", "Share your toys with others.", "和别人分享玩具。"),
    ("signal", "n.", "信号", "初中", "The signal is weak.", "信号很弱。"),
    ("similar", "adj.", "相似的", "初中", "The two books are similar.", "这两本书很相似。"),
    ("social", "adj.", "社会的；社交的", "初中", "He is a social person.", "他善于社交。"),
    ("solve", "v.", "解决", "初中", "Solve the math problem.", "解这道数学题。"),
    ("source", "n.", "来源", "初中", "Books are a source of knowledge.", "书是知识来源。"),
    ("speech", "n.", "演讲；言语", "初中", "He gave a speech.", "他做了演讲。"),
    ("spirit", "n.", "精神", "初中", "Show your team spirit.", "展现团队精神。"),
    ("standard", "n./adj.", "标准", "初中", "This meets the standard.", "这符合标准。"),
    ("strange", "adj.", "奇怪的；陌生的", "初中", "A strange dog came in.", "一只陌生的狗进来了。"),
    ("stress", "n./v.", "压力", "初中", "Don't stress too much.", "别太有压力。"),
    ("strict", "adj.", "严格的", "初中", "Our teacher is strict.", "我们老师很严格。"),
    ("suggest", "v.", "建议", "初中", "I suggest taking a break.", "我建议休息一下。"),
    ("support", "v./n.", "支持", "初中", "My family supports me.", "家人支持我。"),
    ("suppose", "v.", "假设；认为", "初中", "I suppose he is right.", "我想他是对的。"),
    ("survey", "n./v.", "调查", "初中", "We did a survey.", "我们做了一项调查。"),
    ("surprise", "n./v.", "惊喜；使惊讶", "初中", "The gift surprised her.", "礼物让她惊喜。"),
    ("system", "n.", "系统；体系", "初中", "The solar system is huge.", "太阳系很大。"),
    ("technology", "n.", "科技", "初中", "Technology changes life.", "科技改变生活。"),
    ("temperature", "n.", "温度", "初中", "The temperature is high.", "气温很高。"),
    ("though", "conj.", "虽然；尽管", "初中", "He came though he was tired.", "他虽然累还是来了。"),
    ("tradition", "n.", "传统", "初中", "Spring Festival is a tradition.", "春节是个传统。"),
    ("training", "n.", "训练；培训", "初中", "He needs more training.", "他需要更多训练。"),
    ("trust", "v./n.", "信任", "初中", "I trust my friend.", "我信任我的朋友。"),
    ("truth", "n.", "真相；事实", "初中", "Tell me the truth.", "告诉我真相。"),
    ("valuable", "adj.", "有价值的", "初中", "Time is valuable.", "时间很宝贵。"),
    ("various", "adj.", "各种各样的", "初中", "We have various choices.", "我们有各种选择。"),
    ("waste", "v./n.", "浪费；废物", "初中", "Don't waste food.", "别浪费食物。"),
    ("weak", "adj.", "弱的", "初中", "He feels weak today.", "他今天觉得虚弱。"),
    ("wear", "v.", "穿；戴", "初中", "Wear your coat.", "穿上外套。"),
    ("willing", "adj.", "愿意的", "初中", "I am willing to help.", "我愿意帮忙。"),
    ("wonder", "v.", "想知道；惊奇", "初中", "I wonder what happened.", "我想知道发生了什么。"),
    ("worth", "adj.", "值得的", "初中", "The book is worth reading.", "这本书值得读。"),
    ("worried", "adj.", "担心的", "初中", "She is worried about the exam.", "她担心考试。"),

    # ===================== 高中（高阶词） =====================
    ("abandon", "v.", "抛弃；放弃", "高中", "They abandoned the plan.", "他们放弃了计划。"),
    ("absorb", "v.", "吸收；使专注", "高中", "Plants absorb sunlight.", "植物吸收阳光。"),
    ("abstract", "adj.", "抽象的", "高中", "Art can be abstract.", "艺术可以是抽象的。"),
    ("abundant", "adj.", "丰富的；充足的", "高中", "The area has abundant rain.", "该地区雨水充沛。"),
    ("accelerate", "v.", "加速", "高中", "The car accelerated.", "汽车加速了。"),
    ("access", "n./v.", "通道；接近", "高中", "Students have access to the lab.", "学生可以使用实验室。"),
    ("acquire", "v.", "获得；习得", "高中", "He acquired a new skill.", "他掌握了一项新技能。"),
    ("adapt", "v.", "适应；改编", "高中", "We must adapt to changes.", "我们必须适应变化。"),
    ("adequate", "adj.", "足够的；适当的", "高中", "The food is adequate.", "食物足够。"),
    ("adjust", "v.", "调整；适应", "高中", "Adjust your seat, please.", "请调整你的座位。"),
    ("admire", "v.", "钦佩；欣赏", "高中", "I admire her courage.", "我钦佩她的勇气。"),
    ("admit", "v.", "承认；准许进入", "高中", "He admitted his mistake.", "他承认了错误。"),
    ("adopt", "v.", "采纳；收养", "高中", "They adopted a child.", "他们收养了一个孩子。"),
    ("advance", "v./n.", "前进；进步", "高中", "Science continues to advance.", "科学持续进步。"),
    ("adverse", "adj.", "不利的；相反的", "高中", "The weather is adverse.", "天气不利。"),
    ("advocate", "v.", "提倡；拥护", "高中", "He advocates reading daily.", "他提倡每天阅读。"),
    ("affect", "v.", "影响", "高中", "Noise affects sleep.", "噪音影响睡眠。"),
    ("alternative", "n./adj.", "替代物；备选的", "高中", "We need an alternative.", "我们需要备选方案。"),
    ("ambiguous", "adj.", "含糊的；模棱两可的", "高中", "His answer was ambiguous.", "他的回答含糊不清。"),
    ("ambitious", "adj.", "有雄心的", "高中", "She has an ambitious goal.", "她目标远大。"),
    ("analyze", "v.", "分析", "高中", "Analyze the problem first.", "先分析问题。"),
    ("ancestor", "n.", "祖先", "高中", "Our ancestors built this.", "我们的祖先建造了它。"),
    ("announce", "v.", "宣布", "高中", "They announced the result.", "他们宣布了结果。"),
    ("anticipate", "v.", "预期；预料", "高中", "We anticipate a change.", "我们预料会有变化。"),
    ("apparent", "adj.", "明显的；表面的", "高中", "It is apparent to all.", "这一点大家都看得出。"),
    ("appreciate", "v.", "欣赏；感激", "高中", "I appreciate your help.", "感谢你的帮助。"),
    ("approach", "v./n.", "接近；方法", "高中", "Try a new approach.", "尝试新方法。"),
    ("appropriate", "adj.", "合适的", "高中", "Wear appropriate clothes.", "穿合适的衣服。"),
    ("approve", "v.", "批准；赞成", "高中", "The plan was approved.", "计划获批了。"),
    ("arbitrary", "adj.", "武断的；任意的", "高中", "That was an arbitrary choice.", "那是随意的选择。"),
    ("argue", "v.", "争论；主张", "高中", "They argued about it.", "他们为此争论。"),
    ("arise", "v.", "出现；升起", "高中", "A problem arose.", "出现了一个问题。"),
    ("aspect", "n.", "方面", "高中", "Consider every aspect.", "考虑每个方面。"),
    ("assess", "v.", "评估", "高中", "Assess the risk first.", "先评估风险。"),
    ("assist", "v.", "协助", "高中", "She assisted the teacher.", "她协助了老师。"),
    ("assume", "v.", "假定；承担", "高中", "I assume he is right.", "我假定他是对的。"),
    ("astonish", "v.", "使惊讶", "高中", "The news astonished us.", "这消息令我们惊讶。"),
    ("attach", "v.", "附上；系", "高中", "Attach the file, please.", "请附上文件。"),
    ("attain", "v.", "达到；获得", "高中", "He attained his goal.", "他达到了目标。"),
    ("attribute", "v.", "把…归因于", "高中", "We attribute success to effort.", "我们把成功归于努力。"),
    ("authority", "n.", "权威；当局", "高中", "He is an authority on law.", "他是法律权威。"),
    ("aware", "adj.", "意识到的", "高中", "Be aware of the risk.", "要意识到风险。"),
    ("barrier", "n.", "障碍", "高中", "Language is a barrier.", "语言是障碍。"),
    ("brilliant", "adj.", "杰出的；明亮的", "高中", "She is a brilliant student.", "她是位出色的学生。"),
    ("broaden", "v.", "拓宽", "高中", "Travel broadens the mind.", "旅行开阔眼界。"),
    ("circumstance", "n.", "情况；环境", "高中", "Under no circumstance give up.", "无论如何都别放弃。"),
    ("comprehend", "v.", "理解", "高中", "I can't comprehend it.", "我无法理解。"),
    ("conceive", "v.", "构想；怀孕", "高中", "He conceived a plan.", "他构想了一个计划。"),
    ("concrete", "adj.", "具体的", "高中", "Give a concrete example.", "举个具体例子。"),
    ("conduct", "v.", "进行；引导", "高中", "They conducted a test.", "他们做了一项测试。"),
    ("confront", "v.", "面对；对抗", "高中", "Confront the problem.", "直面问题。"),
    ("conscious", "adj.", "有意识的", "高中", "He is conscious now.", "他现在清醒了。"),
    ("consequence", "n.", "后果", "高中", "Face the consequence.", "承担后果。"),
    ("considerable", "adj.", "相当大的", "高中", "It took considerable time.", "花了相当多时间。"),
    ("consist", "v.", "由…组成", "高中", "The team consists of five.", "团队由5人组成。"),
    ("constant", "adj.", "持续的；恒定的", "高中", "Constant practice helps.", "持续练习有帮助。"),
    ("constitute", "v.", "构成；组成", "高中", "Twelve months constitute a year.", "12个月构成一年。"),
    ("contemporary", "adj.", "当代的", "高中", "Contemporary art is popular.", "当代艺术很流行。"),
    ("contribute", "v.", "贡献", "高中", "He contributed to the project.", "他为项目做贡献。"),
    ("controversial", "adj.", "有争议的", "高中", "It is a controversial topic.", "这是个有争议的话题。"),
    ("convey", "v.", "传达；运送", "高中", "Words convey meaning.", "言语传达意义。"),
    ("convince", "v.", "使信服", "高中", "Convince him to join.", "说服他加入。"),
    ("crucial", "adj.", "关键的", "高中", "Timing is crucial.", "时机很关键。"),
    ("cultivate", "v.", "培养；耕作", "高中", "Cultivate good habits.", "培养好习惯。"),
    ("debate", "n./v.", "辩论", "高中", "We had a debate.", "我们展开了辩论。"),
    ("decline", "v./n.", "下降；拒绝", "高中", "Sales declined this year.", "今年销量下降。"),
    ("dedicate", "v.", "奉献", "高中", "He dedicated his life to art.", "他毕生奉献于艺术。"),
    ("define", "v.", "定义", "高中", "Define the word clearly.", "清楚地定义这个词。"),
    ("deliberate", "adj./v.", "故意的；深思", "高中", "It was a deliberate act.", "那是故意的行为。"),
    ("demonstrate", "v.", "证明；演示", "高中", "He demonstrated the method.", "他演示了方法。"),
    ("deny", "v.", "否认", "高中", "He denied the charge.", "他否认了指控。"),
    ("depart", "v.", "离开；出发", "高中", "The train departed.", "火车出发了。"),
    ("derive", "v.", "源于；得出", "高中", "We derive knowledge from books.", "我们从书里获得知识。"),
    ("deserve", "v.", "应得", "高中", "He deserves praise.", "他应受表扬。"),
    ("diminish", "v.", "减少；削弱", "高中", "His influence diminished.", "他的影响力减弱了。"),
    ("distinct", "adj.", "明显的；不同的", "高中", "There is a distinct difference.", "有明显的不同。"),
    ("distribute", "v.", "分发；分布", "高中", "Distribute the books.", "把书分发下去。"),
    ("diverse", "adj.", "多样的", "高中", "The city is culturally diverse.", "这座城市文化多元。"),
    ("dominate", "v.", "支配；主导", "高中", "One team dominated.", "一队占了上风。"),
    ("elaborate", "adj./v.", "详尽的；详述", "高中", "Give an elaborate plan.", "给个详尽的计划。"),
    ("elegant", "adj.", "优雅的", "高中", "She wore an elegant dress.", "她穿了条优雅的裙子。"),
    ("eliminate", "v.", "消除；淘汰", "高中", "Eliminate the error.", "消除错误。"),
    ("emerge", "v.", "出现；浮现", "高中", "The sun emerged.", "太阳出来了。"),
    ("emotional", "adj.", "情绪的；易动情的", "高中", "He is very emotional.", "他很容易动情。"),
    ("emphasize", "v.", "强调", "高中", "She emphasized safety.", "她强调了安全。"),
    ("endure", "v.", "忍受；持续", "高中", "He endured the pain.", "他忍受了疼痛。"),
    ("enhance", "v.", "提高；增强", "高中", "Music enhances mood.", "音乐改善心情。"),
    ("enormous", "adj.", "巨大的", "高中", "An enormous building.", "一座巨大的建筑。"),
    ("ensure", "v.", "确保", "高中", "Ensure the door is locked.", "确保门已锁好。"),
    ("essential", "adj.", "必要的；本质的", "高中", "Water is essential.", "水是必要的。"),
    ("establish", "v.", "建立；确立", "高中", "They established a school.", "他们建了一所学校。"),
    ("estimate", "v./n.", "估计", "高中", "Estimate the cost.", "估算成本。"),
    ("evoke", "v.", "唤起；引起", "高中", "The song evoked memories.", "这首歌唤起了回忆。"),
    ("exceed", "v.", "超过", "高中", "Don't exceed the limit.", "别超过限额。"),
    ("exhaust", "v.", "耗尽；使精疲力竭", "高中", "The trip exhausted him.", "旅途让他筋疲力尽。"),
    ("exhibit", "v./n.", "展览；展现", "高中", "The museum exhibits art.", "博物馆展出艺术品。"),
    ("expand", "v.", "扩大；扩展", "高中", "The business expanded.", "业务扩大了。"),
    ("explicit", "adj.", "明确的", "高中", "Give explicit instructions.", "给出明确指示。"),
    ("exploit", "v.", "开发；利用", "高中", "Exploit the resource wisely.", "明智地开发资源。"),
    ("explore", "v.", "探索", "高中", "Explore the forest.", "探索森林。"),
    ("expose", "v.", "暴露；使接触", "高中", "Don't expose it to light.", "别让它见光。"),
    ("extend", "v.", "延伸；延长", "高中", "Extend the deadline.", "延长期限。"),
    ("external", "adj.", "外部的", "高中", "External factors matter.", "外部因素很重要。"),
    ("fatal", "adj.", "致命的", "高中", "A fatal mistake.", "致命的错误。"),
    ("feasible", "adj.", "可行的", "高中", "The plan is feasible.", "计划可行。"),
    ("finance", "n./v.", "金融；资助", "高中", "Study personal finance.", "学习个人理财。"),
    ("flexible", "adj.", "灵活的", "高中", "We need a flexible plan.", "我们需要灵活的计划。"),
    ("fluctuate", "v.", "波动", "高中", "Prices fluctuate daily.", "价格每天波动。"),
    ("forbid", "v.", "禁止", "高中", "Smoking is forbidden.", "禁止吸烟。"),
    ("foresee", "v.", "预见", "高中", "We couldn't foresee this.", "我们没能预见这点。"),
    ("formal", "adj.", "正式的", "高中", "Wear formal clothes.", "穿正式服装。"),
    ("fragile", "adj.", "脆弱的", "高中", "Glass is fragile.", "玻璃易碎。"),
    ("fundamental", "adj.", "基本的", "高中", "Honesty is fundamental.", "诚实是基本的。"),
    ("genuine", "adj.", "真诚的；真正的", "高中", "A genuine smile.", "真诚的微笑。"),
    ("highlight", "v.", "强调；突出", "高中", "The report highlights risks.", "报告突出了风险。"),
    ("humble", "adj.", "谦逊的", "高中", "He is humble despite fame.", "他虽有名却谦逊。"),
    ("ideal", "adj./n.", "理想的；典范", "高中", "An ideal solution.", "理想的解决方案。"),
    ("identical", "adj.", "完全相同的", "高中", "The twins are identical.", "双胞胎一模一样。"),
    ("ignore", "v.", "忽视", "高中", "Don't ignore the warning.", "别忽视警告。"),
    ("illustrate", "v.", "说明；图解", "高中", "The chart illustrates the trend.", "图表说明了趋势。"),
    ("imitate", "v.", "模仿", "高中", "Children imitate adults.", "孩子模仿大人。"),
    ("impose", "v.", "强加；征收", "高中", "Don't impose your view.", "别把观点强加于人。"),
    ("incentive", "n.", "激励；动机", "高中", "Money is an incentive.", "金钱是一种激励。"),
    ("incident", "n.", "事件", "高中", "A strange incident happened.", "发生了一件怪事。"),
    ("incline", "v.", "倾向于；倾斜", "高中", "I incline to agree.", "我倾向于同意。"),
    ("indicate", "v.", "表明；指示", "高中", "The map indicates the way.", "地图标明了路线。"),
    ("inevitable", "adj.", "不可避免的", "高中", "Change is inevitable.", "变化不可避免。"),
    ("infer", "v.", "推断", "高中", "We can infer the cause.", "我们能推断出原因。"),
    ("influence", "v./n.", "影响", "高中", "Friends influence us.", "朋友影响我们。"),
    ("inhibit", "v.", "抑制；阻止", "高中", "Fear inhibits action.", "恐惧阻碍行动。"),
    ("initial", "adj.", "最初的", "高中", "The initial step is hard.", "第一步很难。"),
    ("innocent", "adj.", "无辜的；天真的", "高中", "He is innocent.", "他是无辜的。"),
    ("inspect", "v.", "检查", "高中", "Inspect the goods.", "检查货物。"),
    ("install", "v.", "安装", "高中", "Install the software.", "安装软件。"),
    ("instinct", "n.", "本能", "高中", "Survival is an instinct.", "求生是本能。"),
    ("integrate", "v.", "整合；使融入", "高中", "Integrate the data.", "整合数据。"),
    ("integrity", "n.", "正直；完整", "高中", "He is a man of integrity.", "他是个正直的人。"),
    ("intense", "adj.", "强烈的", "高中", "Intense heat.", "酷热。"),
    ("interaction", "n.", "互动", "高中", "Social interaction matters.", "社交互动很重要。"),
    ("interpret", "v.", "解释；口译", "高中", "Interpret the result.", "解释结果。"),
    ("involve", "v.", "涉及；使参与", "高中", "The job involves travel.", "这工作要出差。"),
    ("isolate", "v.", "孤立；隔离", "高中", "Isolate the problem.", "把问题孤立出来。"),
    ("keen", "adj.", "热衷的；敏锐的", "高中", "She is keen on music.", "她热衷音乐。"),
    ("logical", "adj.", "逻辑的", "高中", "His argument is logical.", "他的论证合乎逻辑。"),
    ("mature", "adj.", "成熟的", "高中", "He is mature for his age.", "他比同龄人成熟。"),
    ("mechanism", "n.", "机制", "高中", "Understand the mechanism.", "理解机制。"),
    ("merely", "adv.", "仅仅", "高中", "It is merely a test.", "这仅仅是个测试。"),
    ("minimal", "adj.", "最小的", "高中", "Keep errors minimal.", "把错误降到最低。"),
    ("modify", "v.", "修改", "高中", "Modify the design.", "修改设计。"),
    ("monitor", "v./n.", "监视；显示器", "高中", "Monitor your progress.", "监控你的进度。"),
    ("moral", "adj./n.", "道德的；寓意", "高中", "The story has a moral.", "这个故事有寓意。"),
    ("mutual", "adj.", "相互的", "高中", "We have mutual respect.", "我们相互尊重。"),
    ("neglect", "v.", "忽视；疏忽", "高中", "Don't neglect your health.", "别忽视健康。"),
    ("occupy", "v.", "占据", "高中", "The task occupied him.", "任务占用了他时间。"),
    ("occur", "v.", "发生；出现", "高中", "An accident occurred.", "发生了事故。"),
    ("oppose", "v.", "反对", "高中", "They oppose the plan.", "他们反对这计划。"),
    ("optimal", "adj.", "最佳的", "高中", "Find the optimal way.", "找到最佳方式。"),
    ("origin", "n.", "起源", "高中", "The origin of the river.", "这条河的源头。"),
    ("output", "n.", "产出；输出", "高中", "Increase the output.", "提高产量。"),
    ("overcome", "v.", "克服", "高中", "Overcome the difficulty.", "克服困难。"),
    ("overlook", "v.", "忽略；俯瞰", "高中", "Don't overlook details.", "别忽略细节。"),
    ("partial", "adj.", "部分的；偏袒的", "高中", "A partial answer.", "部分回答。"),
    ("participant", "n.", "参与者", "高中", "He is a participant.", "他是一名参与者。"),
    ("particular", "adj.", "特别的；特定的", "高中", "In this particular case.", "在这种特定情况下。"),
    ("passive", "adj.", "被动的", "高中", "Don't be passive.", "别被动。"),
    ("patience", "n.", "耐心", "高中", "It takes patience.", "这需要耐心。"),
    ("perceive", "v.", "察觉；理解", "高中", "We perceive the change.", "我们察觉到变化。"),
    ("permanent", "adj.", "永久的", "高中", "A permanent solution.", "永久的解决办法。"),
    ("permit", "v.", "允许", "高中", "Smoking is not permitted.", "不允许吸烟。"),
    ("persist", "v.", "坚持；持续", "高中", "Persist in your effort.", "坚持努力。"),
    ("perspective", "n.", "视角；观点", "高中", "From my perspective.", "在我看来。"),
    ("phenomenon", "n.", "现象", "高中", "A natural phenomenon.", "一种自然现象。"),
    ("physical", "adj.", "身体的；物理的", "高中", "Physical exercise helps.", "体育锻炼有益。"),
    ("pioneer", "n.", "先驱", "高中", "He is a pioneer in AI.", "他是AI先驱。"),
    ("plausible", "adj.", "看似合理的", "高中", "A plausible excuse.", "看似合理的借口。"),
    ("pose", "v.", "造成；摆姿势", "高中", "It poses a risk.", "这构成风险。"),
    ("positive", "adj.", "积极的；正的", "高中", "Stay positive.", "保持积极。"),
    ("possess", "v.", "拥有", "高中", "He possesses talent.", "他拥有天赋。"),
    ("precise", "adj.", "精确的", "高中", "Give a precise number.", "给个精确数字。"),
    ("predict", "v.", "预测", "高中", "Predict the result.", "预测结果。"),
    ("preserve", "v.", "保护；保存", "高中", "Preserve the forest.", "保护森林。"),
    ("prevail", "v.", "盛行；获胜", "高中", "Justice will prevail.", "正义终将胜出。"),
    ("previous", "adj.", "先前的", "高中", "The previous owner.", "前任主人。"),
    ("principal", "adj./n.", "主要的；校长", "高中", "The principal reason.", "主要原因。"),
    ("prior", "adj.", "优先的；先前的", "高中", "Prior to the meeting.", "会议之前。"),
    ("privilege", "n.", "特权；荣幸", "高中", "It is a privilege to be here.", "在此是一种荣幸。"),
    ("proceed", "v.", "继续进行", "高中", "Proceed with the plan.", "继续执行计划。"),
    ("profound", "adj.", "深刻的", "高中", "A profound idea.", "深刻的思想。"),
    ("prohibit", "v.", "禁止", "高中", "The law prohibits it.", "法律禁止此事。"),
    ("prominent", "adj.", "突出的；著名的", "高中", "A prominent scientist.", "一位著名科学家。"),
    ("promote", "v.", "促进；晋升", "高中", "Promote healthy habits.", "倡导健康习惯。"),
    ("propose", "v.", "提议；求婚", "高中", "He proposed a plan.", "他提出了一个计划。"),
    ("prospect", "n.", "前景；展望", "高中", "The job has good prospects.", "这工作前景好。"),
    ("prosperous", "adj.", "繁荣的", "高中", "A prosperous city.", "繁荣的城市。"),
    ("protect", "v.", "保护", "高中", "Protect the environment.", "保护环境。"),
    ("publish", "v.", "出版；发布", "高中", "He published a book.", "他出版了一本书。"),
    ("pursue", "v.", "追求；从事", "高中", "Pursue your dream.", "追求你的梦想。"),
    ("qualify", "v.", "使合格；取得资格", "高中", "He qualified for the race.", "他有资格参赛。"),
    ("react", "v.", "反应", "高中", "How did he react?", "他有何反应？"),
    ("realistic", "adj.", "现实的", "高中", "Set a realistic goal.", "定个现实的目标。"),
    ("recall", "v.", "回忆；召回", "高中", "I recall the day.", "我回想起那天。"),
    ("recover", "v.", "恢复；找回", "高中", "He recovered quickly.", "他恢复得很快。"),
    ("reflect", "v.", "反映；反思", "高中", "Reflect on your mistake.", "反思你的错误。"),
    ("reform", "v./n.", "改革", "高中", "Education reform.", "教育改革。"),
    ("reinforce", "v.", "加强", "高中", "Reinforce the wall.", "加固墙体。"),
    ("relate", "v.", "有关联；讲述", "高中", "Relate to others.", "与他人建立联系。"),
    ("release", "v.", "释放；发布", "高中", "Release the news.", "发布消息。"),
    ("relevant", "adj.", "相关的", "高中", "Give relevant examples.", "举相关的例子。"),
    ("relieve", "v.", "缓解；减轻", "高中", "The medicine relieves pain.", "药缓解疼痛。"),
    ("rely", "v.", "依赖", "高中", "Rely on yourself.", "依靠自己。"),
    ("remarkable", "adj.", "非凡的", "高中", "A remarkable achievement.", "非凡的成就。"),
    ("remote", "adj.", "偏远的；远程的", "高中", "A remote village.", "偏远的村庄。"),
    ("remove", "v.", "移除", "高中", "Remove the stain.", "去掉污渍。"),
    ("replace", "v.", "取代；更换", "高中", "Replace the battery.", "更换电池。"),
    ("represent", "v.", "代表；象征", "高中", "He represents our class.", "他代表我们班。"),
    ("reputation", "n.", "声誉", "高中", "He has a good reputation.", "他声誉很好。"),
    ("resist", "v.", "抵抗", "高中", "Resist temptation.", "抵制诱惑。"),
    ("resolve", "v.", "解决；决心", "高中", "Resolve the conflict.", "解决冲突。"),
    ("respond", "v.", "回应", "高中", "She didn't respond.", "她没有回应。"),
    ("restore", "v.", "恢复；修复", "高中", "Restore the old building.", "修复老建筑。"),
    ("restrict", "v.", "限制", "高中", "Restrict the speed.", "限制速度。"),
    ("retain", "v.", "保留", "高中", "Retain the information.", "记住这些信息。"),
    ("reveal", "v.", "揭示；透露", "高中", "The report reveals the truth.", "报告揭示了真相。"),
    ("reverse", "v./adj.", "反转；相反的", "高中", "Reverse the car.", "倒车。"),
    ("reward", "n./v.", "奖励", "高中", "Hard work brings reward.", "努力带来回报。"),
    ("rigid", "adj.", "僵硬的；严格的", "高中", "A rigid rule.", "死板的规则。"),
    ("robust", "adj.", "强健的；稳健的", "高中", "A robust system.", "稳健的系统。"),
    ("scope", "n.", "范围", "高中", "Within the scope.", "在范围内。"),
    ("secure", "adj./v.", "安全的；获得", "高中", "Secure the data.", "保护数据安全。"),
    ("seek", "v.", "寻求", "高中", "Seek the truth.", "寻求真相。"),
    ("select", "v./adj.", "选择；精选的", "高中", "Select a book.", "选一本书。"),
    ("sensitive", "adj.", "敏感的", "高中", "Be sensitive to others.", "对他人要敏感。"),
    ("sequence", "n.", "顺序；序列", "高中", "In the right sequence.", "按正确顺序。"),
    ("session", "n.", "会议；时段", "高中", "A training session.", "一次培训。"),
    ("sheer", "adj.", "纯粹的；陡峭的", "高中", "Sheer luck.", "纯属运气。"),
    ("shelter", "n./v.", "庇护；避难所", "高中", "Seek shelter from rain.", "找地方避雨。"),
    ("shift", "v./n.", "转移；轮班", "高中", "Shift your focus.", "转移注意力。"),
    ("significance", "n.", "重要性；意义", "高中", "The significance of the event.", "事件的意义。"),
    ("sincere", "adj.", "真诚的", "高中", "A sincere apology.", "真诚的道歉。"),
    ("slight", "adj.", "轻微的", "高中", "A slight change.", "轻微的变化。"),
    ("sophisticated", "adj.", "复杂的；老练的", "高中", "A sophisticated machine.", "精密的机器。"),
    ("specific", "adj.", "具体的；特定的", "高中", "Be specific, please.", "请具体些。"),
    ("stable", "adj.", "稳定的", "高中", "A stable economy.", "稳定的经济。"),
    ("stimulate", "v.", "刺激；激发", "高中", "Stimulate interest.", "激发兴趣。"),
    ("strategy", "n.", "策略", "高中", "A clear strategy.", "清晰的策略。"),
    ("subsequent", "adj.", "随后的", "高中", "In subsequent years.", "在随后的几年里。"),
    ("substance", "n.", "物质；实质", "高中", "A harmful substance.", "有害物质。"),
    ("subtle", "adj.", "微妙的", "高中", "A subtle difference.", "微妙的差别。"),
    ("sufficient", "adj.", "充足的", "高中", "Is food sufficient?", "食物够吗？"),
    ("superior", "adj.", "优越的；上级的", "高中", "A superior method.", "更优的方法。"),
    ("supplement", "n./v.", "补充", "高中", "Take a supplement.", "吃点补充剂。"),
    ("supply", "v./n.", "供应", "高中", "Supply the demand.", "满足需求。"),
    ("supreme", "adj.", "最高的", "高中", "The supreme court.", "最高法院。"),
    ("survive", "v.", "生存", "高中", "They survived the storm.", "他们在风暴中幸存。"),
    ("suspect", "v.", "怀疑", "高中", "I suspect a lie.", "我怀疑有假。"),
    ("suspend", "v.", "暂停；悬挂", "高中", "Classes were suspended.", "课程暂停。"),
    ("sustain", "v.", "维持；支撑", "高中", "Sustain the effort.", "维持努力。"),
    ("symbol", "n.", "象征", "高中", "The dove is a symbol of peace.", "鸽子是和平的象征。"),
    ("sympathy", "n.", "同情", "高中", "Show sympathy.", "表示同情。"),
    ("tackle", "v.", "处理； tackling", "高中", "Tackle the problem.", "处理这个问题。"),
    ("tactic", "n.", "策略；战术", "高中", "A useful tactic.", "有用的策略。"),
    ("target", "n./v.", "目标；瞄准", "高中", "Reach the target.", "达成目标。"),
    ("temporary", "adj.", "临时的", "高中", "A temporary job.", "临时工作。"),
    ("tend", "v.", "倾向于", "高中", "People tend to forget.", "人容易忘记。"),
    ("tension", "n.", "紧张；张力", "高中", "Reduce tension.", "缓解紧张。"),
    ("terminal", "adj./n.", "终端；晚期的", "高中", "The bus terminal.", "公交总站。"),
    ("territory", "n.", "领土；领域", "高中", "Defend the territory.", "保卫领土。"),
    ("thrust", "v./n.", "推进；刺", "高中", "Thrust forward.", "向前推进。"),
    ("tolerate", "v.", "容忍", "高中", "I can't tolerate noise.", "我受不了噪音。"),
    ("trace", "v./n.", "追踪；痕迹", "高中", "Trace the source.", "追根溯源。"),
    ("transform", "v.", "转变", "高中", "Technology transforms life.", "科技改变生活。"),
    ("transit", "n.", "运输；中转", "高中", "Public transit.", "公共交通。"),
    ("transparent", "adj.", "透明的；清晰的", "高中", "A transparent process.", "透明的流程。"),
    ("trap", "n./v.", "陷阱；困住", "高中", "Avoid the trap.", "避开陷阱。"),
    ("trend", "n.", "趋势", "高中", "A rising trend.", "上升的趋势。"),
    ("trial", "n.", "审判；试验", "高中", "A clinical trial.", "临床试验。"),
    ("trigger", "v./n.", "触发；扳机", "高中", "The error triggered a crash.", "错误引发了崩溃。"),
    ("ultimate", "adj.", "最终的", "高中", "The ultimate goal.", "最终目标。"),
    ("undergo", "v.", "经历；承受", "高中", "Undergo training.", "接受训练。"),
    ("underlying", "adj.", "潜在的；根本的", "高中", "The underlying cause.", "根本原因。"),
    ("uniform", "n./adj.", "制服；一致的", "高中", "Wear a uniform.", "穿制服。"),
    ("unique", "adj.", "独特的", "高中", "A unique style.", "独特的风格。"),
    ("universal", "adj.", "普遍的", "高中", "A universal truth.", "普遍的真理。"),
    ("update", "v.", "更新", "高中", "Update the app.", "更新应用。"),
    ("utilize", "v.", "利用", "高中", "Utilize the tool.", "利用这个工具。"),
    ("utter", "v./adj.", "说出；完全的", "高中", "Not an utter word.", "一言不发。"),
    ("valid", "adj.", "有效的；合理的", "高中", "A valid reason.", "合理的理由。"),
    ("vanish", "v.", "消失", "高中", "The fog vanished.", "雾散了。"),
    ("variable", "n./adj.", "变量；可变的", "高中", "Control the variable.", "控制变量。"),
    ("vast", "adj.", "广阔的", "高中", "A vast ocean.", "广阔的海洋。"),
    ("venture", "v./n.", "冒险；企业", "高中", "Venture into business.", "投身商界。"),
    ("verify", "v.", "核实", "高中", "Verify the data.", "核实数据。"),
    ("vigorous", "adj.", "有力的；精力充沛的", "高中", "A vigorous exercise.", "剧烈的运动。"),
    ("virtual", "adj.", "虚拟的", "高中", "A virtual meeting.", "虚拟会议。"),
    ("visible", "adj.", "可见的", "高中", "The stars are visible.", "星星可见。"),
    ("vision", "n.", "视力；愿景", "高中", "A clear vision.", "清晰的愿景。"),
    ("vital", "adj.", "至关重要的", "高中", "Sleep is vital.", "睡眠至关重要。"),
    ("volume", "n.", "音量；体积", "高中", "Turn up the volume.", "调高音量。"),
    ("voluntary", "adj.", "自愿的", "高中", "Voluntary work.", "志愿工作。"),
    ("wage", "n./v.", "工资；发动", "高中", "A fair wage.", "合理的工资。"),
    ("wealth", "n.", "财富", "高中", "Health is wealth.", "健康就是财富。"),
    ("weary", "adj.", "疲倦的", "高中", "A weary traveler.", "疲惫的旅人。"),
    ("welfare", "n.", "福利", "高中", "Social welfare.", "社会福利。"),
    ("whereas", "conj.", "然而；鉴于", "高中", "He is rich, whereas I am poor.", "他富有，而我贫穷。"),
    ("witness", "v./n.", "目击；证人", "高中", "He witnessed the event.", "他目击了事件。"),
    ("yield", "v.", "产出；屈服", "高中", "The field yields corn.", "田地出产玉米。"),
    ("zone", "n.", "区域", "高中", "A war zone.", "战区。"),
]


def main():
    merged = {}
    # 现有种子（标初中）
    for w in seed:
        merged[w["word"].lower()] = w
    # 新增
    added = 0
    for item in ADD:
        word, pos, zh, level, ex, exc = item
        key = word.lower()
        if key in merged:
            continue
        merged[key] = {
            "word": word,
            "phonetic": "",
            "pos": pos,
            "meaning": zh,
            "example": ex,
            "example_cn": exc,
            "level": level,
        }
        added += 1
    words = list(merged.values())
    # 稳定排序：按学段(小学<初中<高中)再按字母
    order = {"小学": 0, "初中": 1, "高中": 2, "自定义": 3}
    words.sort(key=lambda w: (order.get(w.get("level", "初中"), 1), w["word"].lower()))
    data = {
        "meta": {
            "name": "K12 核心词汇（离线课标语料库）",
            "note": "覆盖小/初/高常见考点，按学段标注。可在「单词卡」手动添加，或接词典 API 批量扩充。",
            "version": "2.0",
        },
        "words": words,
    }
    WORDS_FILE.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    from collections import Counter
    cnt = Counter(w.get("level", "初中") for w in words)
    print(f"写出词库：共 {len(words)} 词（新增 {added}）")
    for lv in ["小学", "初中", "高中", "自定义"]:
        if cnt.get(lv):
            print(f"  {lv}: {cnt[lv]}")


if __name__ == "__main__":
    main()
